version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: projeto-fintech
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fintech-net

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8088:8080
    networks:
      - fintech-net

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local-fintech
    ports:
      - 8010:8000
    command: "-jar DynamoDBLocal.jar -sharedDb"
    networks:
      - fintech-net

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    depends_on:
      - dynamodb
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8010
    ports:
      - 8011:8001
    networks:
      - fintech-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-fintech
    ports:
      - 5672:5672      # Porta padrão de comunicação com RabbitMQ
      - 15672:15672    # Porta para acessar a interface de gerenciamento do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - fintech-net

volumes:
  mysql_data:

networks:
  fintech-net:
