version: '3'
services:


  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: projeto-fintech
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080
volumes:
  mysql_data: