### Teste de Criação de Usuário
POST http://localhost:8881/users
Content-Type: application/json

{

  "name": "joao",
  "email": "joao.sislv2a@example.com",
  "password": "senha1232",
  "cpf": "12345673931"
}

### Request transferencia
POST http://localhost:8881/transaction
Content-Type: application/json

{
  "from_account_id": "0492eab8-89a7-49cb-a3b4-be147f2ad592",
  "to_account_id": "b0b012b2-4423-47c4-9148-49496d89ea3d",
  "amount": 100
}


### Request transferencia trabalho
POST http://localhost:8881/transaction
Content-Type: application/json

{
  "from_account_id": "13d9f7dd-38ba-4270-be66-888063029b87",
  "to_account_id": "54c94560-e552-44fd-95d4-59a5af796d92",
  "amount": 100
}


